name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Step 4: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_ACR_LOGIN_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      # Step 6: Build Docker images for the microservices
      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/book_catalog:latest ./book_catalog
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/inventory_management:latest ./inventory_management

      # Step 7: Push the images to Azure Container Registry (ACR)
      - name: Push Docker images to ACR
        run: |
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/book_catalog:latest
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/inventory_management:latest

      # Step 9: Deploy to Azure Kubernetes Service (AKS)
      - name: Apply Kubernetes deployment
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
          run: |
            kubectl apply -f ./scripts/kubernetes/deployment.yml


