name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Give write permissions to id-token
  contents: read   # Read permission for the code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Azure Login using OIDC token
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Init
      - name: Terraform Init
        working-directory: ./scripts
        run: terraform init

      # Step 5: Terraform Apply
      - name: Terraform Apply
        working-directory: ./scripts
        run: terraform apply -auto-approve

      # Step 6: Get ACR name from Terraform output
      - name: Get ACR Name
        id: acr_info
        working-directory: ./scripts
        run: |
          ACR_NAME=$(terraform output -raw acr_name)
          echo "::set-output name=acr_name::$ACR_NAME"

      # Step 7: Enable ACR Admin
      - name: Enable ACR Admin
        run: |
          ACR_NAME=${{ steps.acr_info.outputs.acr_name }}
          az acr update --name $ACR_NAME --admin-enabled true
