name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Step 4: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_ACR_LOGIN_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      # Step 6: Build Docker images for the microservices
      - name: Build and tag Docker images
        run: |
          docker build -t rajpal151.azurecr.io/book_catalog:latest ./book_catalog
          docker build -t rajpal151.azurecr.io/inventory_management:latest ./inventory_management

      # Step 9: Push Docker images to Azure Container Registry (ACR)
      - name: Push Docker images to ACR
        run: |
          docker push rajpal151.azurecr.io/book_catalog:latest
          docker push rajpal151.azurecr.io/inventory_management:latest

      # Step 8: Set up kubectl and deploy to Azure Kubernetes Service (AKS)
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      # Deploy the services
      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
