name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Step 4: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Build Docker images for the microservices
      - name: Build and tag Docker images
        run: |
          docker build -t rajpal151.azurecr.io/book_catalog:latest ./book_catalog
          docker build -t rajpal151.azurecr.io/inventory_management:latest ./inventory_management

      # Step 6: Push the images to Azure Container Registry (ACR)
      - name: Push Docker images to ACR
        run: |
          docker push rajpal151.azurecr.io/book_catalog:latest
          docker push rajpal151.azurecr.io/inventory_management:latest

      # Step 7: Deploy to Azure Kubernetes Service (AKS)
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
          run: |
            kubectl apply -f ./scripts/kubernetes/deployment.yml
